services:
  mysql:
    image: mysql:8
    container_name: realestate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realestate_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
