services:
  mysql:
    image: mysql:8.0
    container_name: realestate_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realestate_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
